name: Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 6'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      
      - name: Disk free
        run: |
          echo "Free disk space:"
          df -h
      
      - uses: actions/checkout@v4

      - name: Set up QEMU        
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx        
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin docker.io

      - name: Build base
        working-directory: ./docker/base
        run: |
          export MAINTAINER="infosux"
          export BUILD_DATE=$(date -u +"%Y-%m-%d")
          export BUILD_TIME=$(date -u +"%H:%M:%S UTC")
          export VCS_URL=$(git config --get remote.origin.url)
          export VCS_REF=$(git rev-parse --short HEAD)
          docker buildx build --build-arg MAINTAINER --build-arg BUILD_DATE --build-arg BUILD_TIME -t ${{ secrets.DOCKER_USERNAME }}/haxtools:base --push --platform=linux/arm64,linux/amd64 .
          docker system prune -af

      - name: Build cli
        working-directory: ./docker/cli
        run: |
          export MAINTAINER="infosux"
          export BUILD_DATE=$(date -u +"%Y-%m-%d")
          export BUILD_TIME=$(date -u +"%H:%M:%S UTC")
          export VCS_URL=$(git config --get remote.origin.url)
          export VCS_REF=$(git rev-parse --short HEAD)
          docker buildx build --build-arg MAINTAINER --build-arg BUILD_DATE --build-arg BUILD_TIME -t ${{ secrets.DOCKER_USERNAME }}/haxtools:cli --push --platform=linux/arm64,linux/amd64 .
          docker system prune -af

      - name: Build full
        working-directory: ./docker/gui
        run: |
          export MAINTAINER="infosux"
          export BUILD_DATE=$(date -u +"%Y-%m-%d")
          export BUILD_TIME=$(date -u +"%H:%M:%S UTC")
          export VCS_URL=$(git config --get remote.origin.url)
          export VCS_REF=$(git rev-parse --short HEAD)
          docker buildx build --build-arg MAINTAINER --build-arg BUILD_DATE --build-arg BUILD_TIME -t ${{ secrets.DOCKER_USERNAME }}/haxtools:gui --push --platform=linux/arm64,linux/amd64 .
          docker system prune -af
